version: '3'

services:
  app:
    build:
      context: ./
      args:
        VIDEO_DIRECTORY: ${VIDEO_DIRECTORY}
        IMAGE_DIRECTORY: ${IMAGE_DIRECTORY}
    container_name: video_app
    depends_on:
      - postgres
    env_file:
      - .env
    restart: always
    networks:
      global_network:
      default:
    volumes:
      - videoapi-storage:/home/python/${VIDEO_DIRECTORY}
      - videoapi-image-storage:/home/python/${IMAGE_DIRECTORY}

  postgres:
    image: postgres:latest
    container_name: video_db
    restart: always
    env_file:
      - .env
    networks:
      default:

networks:
  global_network:
    external: true
volumes:
  videoapi-storage:
  videoapi-image-storage:
