"""add app_bundle

Revision ID: 0771e3f3d06c
Revises: ba095b2261c4
Create Date: 2025-01-23 14:44:24.101401

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0771e3f3d06c'
down_revision = 'ba095b2261c4'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('videos', sa.Column('app_bundle', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('videos', 'app_bundle')
    # ### end Alembic commands ###
